/* This file was generated by SableCC (http://www.sablecc.org/). */

package Epl.analysis;

import Epl.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object in);
    Object getOut(Node node);
    void setOut(Node node, Object out);

    void caseStart(Start node);
    void caseAProgram(AProgram node);
    void caseABralist(ABralist node);
    void caseAList(AList node);
    void caseAHead(AHead node);
    void caseANonf(ANonf node);
    void caseANonp(ANonp node);
    void caseANonfin(ANonfin node);
    void caseANonprod(ANonprod node);
    void caseAAtom(AAtom node);
    void caseATarget(ATarget node);
    void caseAResource(AResource node);
    void caseATechnique(ATechnique node);
    void caseAProduct(AProduct node);
    void caseAProducttail(AProducttail node);
    void caseAJointProducttail(AJointProducttail node);
    void caseAResstatStatement(AResstatStatement node);
    void caseATechstatStatement(ATechstatStatement node);
    void caseAFtechstatStatement(AFtechstatStatement node);
    void caseATargstatStatement(ATargstatStatement node);
    void caseAFinalstatStatement(AFinalstatStatement node);
    void caseAProdstatStatement(AProdstatStatement node);
    void caseAStatementlist(AStatementlist node);
    void caseAStatements(AStatements node);

    void caseTFloatingConstant(TFloatingConstant node);
    void caseTFrozen(TFrozen node);
    void caseTTech(TTech node);
    void caseTRes(TRes node);
    void caseTTarg(TTarg node);
    void caseTNonft(TNonft node);
    void caseTNonpt(TNonpt node);
    void caseTBra(TBra node);
    void caseTKet(TKet node);
    void caseTSemicolon(TSemicolon node);
    void caseTArrow(TArrow node);
    void caseTIdentifier(TIdentifier node);
    void caseTBlank(TBlank node);
    void caseTComment(TComment node);
    void caseTCodecomment(TCodecomment node);
    void caseEOF(EOF node);
}
