/* This file was generated by SableCC (http://www.sablecc.org/). */

package Epl.node;

import java.util.*;
import Epl.analysis.*;

public final class AAtom extends PAtom
{
    private TFloatingConstant _floatingConstant_;
    private TIdentifier _identifier_;

    public AAtom()
    {
    }

    public AAtom(
        TFloatingConstant _floatingConstant_,
        TIdentifier _identifier_)
    {
        setFloatingConstant(_floatingConstant_);

        setIdentifier(_identifier_);

    }
    public Object clone()
    {
        return new AAtom(
            (TFloatingConstant) cloneNode(_floatingConstant_),
            (TIdentifier) cloneNode(_identifier_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAtom(this);
    }

    public TFloatingConstant getFloatingConstant()
    {
        return _floatingConstant_;
    }

    public void setFloatingConstant(TFloatingConstant node)
    {
        if(_floatingConstant_ != null)
        {
            _floatingConstant_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _floatingConstant_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return _identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_floatingConstant_)
            + toString(_identifier_);
    }

    void removeChild(Node child)
    {
        if(_floatingConstant_ == child)
        {
            _floatingConstant_ = null;
            return;
        }

        if(_identifier_ == child)
        {
            _identifier_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_floatingConstant_ == oldChild)
        {
            setFloatingConstant((TFloatingConstant) newChild);
            return;
        }

        if(_identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

    }
}
