/* This file was generated by SableCC (http://www.sablecc.org/). */

package Epl.node;

import java.util.*;
import Epl.analysis.*;

public final class AFinalstatStatement extends PStatement
{
    private PNonfin _nonfin_;

    public AFinalstatStatement()
    {
    }

    public AFinalstatStatement(
        PNonfin _nonfin_)
    {
        setNonfin(_nonfin_);

    }
    public Object clone()
    {
        return new AFinalstatStatement(
            (PNonfin) cloneNode(_nonfin_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFinalstatStatement(this);
    }

    public PNonfin getNonfin()
    {
        return _nonfin_;
    }

    public void setNonfin(PNonfin node)
    {
        if(_nonfin_ != null)
        {
            _nonfin_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _nonfin_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_nonfin_);
    }

    void removeChild(Node child)
    {
        if(_nonfin_ == child)
        {
            _nonfin_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_nonfin_ == oldChild)
        {
            setNonfin((PNonfin) newChild);
            return;
        }

    }
}
