/* This file was generated by SableCC (http://www.sablecc.org/). */

package Epl.node;

import java.util.*;
import Epl.analysis.*;

public final class AJointProduct extends PProduct
{
    private PBralist _bralist_;

    public AJointProduct()
    {
    }

    public AJointProduct(
        PBralist _bralist_)
    {
        setBralist(_bralist_);

    }
    public Object clone()
    {
        return new AJointProduct(
            (PBralist) cloneNode(_bralist_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAJointProduct(this);
    }

    public PBralist getBralist()
    {
        return _bralist_;
    }

    public void setBralist(PBralist node)
    {
        if(_bralist_ != null)
        {
            _bralist_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _bralist_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_bralist_);
    }

    void removeChild(Node child)
    {
        if(_bralist_ == child)
        {
            _bralist_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_bralist_ == oldChild)
        {
            setBralist((PBralist) newChild);
            return;
        }

    }
}
