/* This file was generated by SableCC (http://www.sablecc.org/). */

package Epl.node;

import java.util.*;
import Epl.analysis.*;

public final class AProgram extends PProgram
{
    private PStatementlist _statementlist_;

    public AProgram()
    {
    }

    public AProgram(
        PStatementlist _statementlist_)
    {
        setStatementlist(_statementlist_);

    }
    public Object clone()
    {
        return new AProgram(
            (PStatementlist) cloneNode(_statementlist_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgram(this);
    }

    public PStatementlist getStatementlist()
    {
        return _statementlist_;
    }

    public void setStatementlist(PStatementlist node)
    {
        if(_statementlist_ != null)
        {
            _statementlist_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _statementlist_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_statementlist_);
    }

    void removeChild(Node child)
    {
        if(_statementlist_ == child)
        {
            _statementlist_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_statementlist_ == oldChild)
        {
            setStatementlist((PStatementlist) newChild);
            return;
        }

    }
}
