/* This file was generated by SableCC (http://www.sablecc.org/). */

package Epl.node;

import java.util.*;
import Epl.analysis.*;

public final class AProduct extends PProduct
{
    private PProducttail _producttail_;

    public AProduct()
    {
    }

    public AProduct(
        PProducttail _producttail_)
    {
        setProducttail(_producttail_);

    }
    public Object clone()
    {
        return new AProduct(
            (PProducttail) cloneNode(_producttail_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProduct(this);
    }

    public PProducttail getProducttail()
    {
        return _producttail_;
    }

    public void setProducttail(PProducttail node)
    {
        if(_producttail_ != null)
        {
            _producttail_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _producttail_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_producttail_);
    }

    void removeChild(Node child)
    {
        if(_producttail_ == child)
        {
            _producttail_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_producttail_ == oldChild)
        {
            setProducttail((PProducttail) newChild);
            return;
        }

    }
}
