/* This file was generated by SableCC (http://www.sablecc.org/). */

package Epl.node;

import java.util.*;
import Epl.analysis.*;

public final class AResstatStatement extends PStatement
{
    private PResource _resource_;

    public AResstatStatement()
    {
    }

    public AResstatStatement(
        PResource _resource_)
    {
        setResource(_resource_);

    }
    public Object clone()
    {
        return new AResstatStatement(
            (PResource) cloneNode(_resource_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAResstatStatement(this);
    }

    public PResource getResource()
    {
        return _resource_;
    }

    public void setResource(PResource node)
    {
        if(_resource_ != null)
        {
            _resource_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _resource_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_resource_);
    }

    void removeChild(Node child)
    {
        if(_resource_ == child)
        {
            _resource_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_resource_ == oldChild)
        {
            setResource((PResource) newChild);
            return;
        }

    }
}
