/* This file was generated by SableCC (http://www.sablecc.org/). */

package Epl.node;

import java.util.*;
import Epl.analysis.*;

public final class ATargstatStatement extends PStatement
{
    private PTarget _target_;

    public ATargstatStatement()
    {
    }

    public ATargstatStatement(
        PTarget _target_)
    {
        setTarget(_target_);

    }
    public Object clone()
    {
        return new ATargstatStatement(
            (PTarget) cloneNode(_target_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATargstatStatement(this);
    }

    public PTarget getTarget()
    {
        return _target_;
    }

    public void setTarget(PTarget node)
    {
        if(_target_ != null)
        {
            _target_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _target_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_target_);
    }

    void removeChild(Node child)
    {
        if(_target_ == child)
        {
            _target_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_target_ == oldChild)
        {
            setTarget((PTarget) newChild);
            return;
        }

    }
}
