/* This file was generated by SableCC (http://www.sablecc.org/). */

package Epl.node;

import Epl.analysis.*;

public final class TBra extends Token
{
    public TBra()
    {
        super.setText("[");
    }

    public TBra(int line, int pos)
    {
        super.setText("[");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TBra(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTBra(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TBra text.");
    }
}
