/* This file was generated by SableCC (http://www.sablecc.org/). */

package Epl.node;

import Epl.analysis.*;

public final class TKet extends Token
{
    public TKet()
    {
        super.setText("]");
    }

    public TKet(int line, int pos)
    {
        super.setText("]");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TKet(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKet(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TKet text.");
    }
}
