/* This file was generated by SableCC (http://www.sablecc.org/). */

package Epl.node;

import Epl.analysis.*;

public final class TNonft extends Token
{
    public TNonft()
    {
        super.setText("Nonfinal");
    }

    public TNonft(int line, int pos)
    {
        super.setText("Nonfinal");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TNonft(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNonft(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TNonft text.");
    }
}
