/* This file was generated by SableCC (http://www.sablecc.org/). */

package Epl.node;

import Epl.analysis.*;

public final class TRes extends Token
{
    public TRes()
    {
        super.setText("Resource");
    }

    public TRes(int line, int pos)
    {
        super.setText("Resource");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TRes(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRes(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TRes text.");
    }
}
