/* This file was generated by SableCC (http://www.sablecc.org/). */

package Epl.node;

import Epl.analysis.*;

public final class TTech extends Token
{
    public TTech()
    {
        super.setText("Technique");
    }

    public TTech(int line, int pos)
    {
        super.setText("Technique");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TTech(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTech(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TTech text.");
    }
}
