/* This file was generated by SableCC (http://www.sablecc.org/). */

package Epl.node;

import Epl.analysis.*;

public final class X1PAtom extends XPAtom
{
    private XPAtom _xPAtom_;
    private PAtom _pAtom_;

    public X1PAtom()
    {
    }

    public X1PAtom(
        XPAtom _xPAtom_,
        PAtom _pAtom_)
    {
        setXPAtom(_xPAtom_);
        setPAtom(_pAtom_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XPAtom getXPAtom()
    {
        return _xPAtom_;
    }

    public void setXPAtom(XPAtom node)
    {
        if(_xPAtom_ != null)
        {
            _xPAtom_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xPAtom_ = node;
    }

    public PAtom getPAtom()
    {
        return _pAtom_;
    }

    public void setPAtom(PAtom node)
    {
        if(_pAtom_ != null)
        {
            _pAtom_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pAtom_ = node;
    }

    void removeChild(Node child)
    {
        if(_xPAtom_ == child)
        {
            _xPAtom_ = null;
        }

        if(_pAtom_ == child)
        {
            _pAtom_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xPAtom_) +
            toString(_pAtom_);
    }
}
