/* This file was generated by SableCC (http://www.sablecc.org/). */

package Epl.node;

import Epl.analysis.*;

public final class X1PStatements extends XPStatements
{
    private XPStatements _xPStatements_;
    private PStatements _pStatements_;

    public X1PStatements()
    {
    }

    public X1PStatements(
        XPStatements _xPStatements_,
        PStatements _pStatements_)
    {
        setXPStatements(_xPStatements_);
        setPStatements(_pStatements_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XPStatements getXPStatements()
    {
        return _xPStatements_;
    }

    public void setXPStatements(XPStatements node)
    {
        if(_xPStatements_ != null)
        {
            _xPStatements_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xPStatements_ = node;
    }

    public PStatements getPStatements()
    {
        return _pStatements_;
    }

    public void setPStatements(PStatements node)
    {
        if(_pStatements_ != null)
        {
            _pStatements_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pStatements_ = node;
    }

    void removeChild(Node child)
    {
        if(_xPStatements_ == child)
        {
            _xPStatements_ = null;
        }

        if(_pStatements_ == child)
        {
            _pStatements_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xPStatements_) +
            toString(_pStatements_);
    }
}
