/* This file was generated by SableCC (http://www.sablecc.org/). */

package Epl.node;

import Epl.analysis.*;

public final class X2PNonp extends XPNonp
{
    private PNonp _pNonp_;

    public X2PNonp()
    {
    }

    public X2PNonp(
        PNonp _pNonp_)
    {
        setPNonp(_pNonp_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PNonp getPNonp()
    {
        return _pNonp_;
    }

    public void setPNonp(PNonp node)
    {
        if(_pNonp_ != null)
        {
            _pNonp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pNonp_ = node;
    }

    void removeChild(Node child)
    {
        if(_pNonp_ == child)
        {
            _pNonp_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pNonp_);
    }
}
