/* This file was generated by SableCC (http://www.sablecc.org/). */

package Epl.node;

import Epl.analysis.*;

public final class X2PNonf extends XPNonf
{
    private PNonf _pNonf_;

    public X2PNonf()
    {
    }

    public X2PNonf(
        PNonf _pNonf_)
    {
        setPNonf(_pNonf_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PNonf getPNonf()
    {
        return _pNonf_;
    }

    public void setPNonf(PNonf node)
    {
        if(_pNonf_ != null)
        {
            _pNonf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pNonf_ = node;
    }

    void removeChild(Node child)
    {
        if(_pNonf_ == child)
        {
            _pNonf_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pNonf_);
    }
}
