/* This file was generated by SableCC (http://www.sablecc.org/). */

package Epl.node;

import Epl.analysis.*;

public final class X2PNonprodid extends XPNonprodid
{
    private PNonprodid _pNonprodid_;

    public X2PNonprodid()
    {
    }

    public X2PNonprodid(
        PNonprodid _pNonprodid_)
    {
        setPNonprodid(_pNonprodid_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PNonprodid getPNonprodid()
    {
        return _pNonprodid_;
    }

    public void setPNonprodid(PNonprodid node)
    {
        if(_pNonprodid_ != null)
        {
            _pNonprodid_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pNonprodid_ = node;
    }

    void removeChild(Node child)
    {
        if(_pNonprodid_ == child)
        {
            _pNonprodid_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pNonprodid_);
    }
}
