/* This file was generated by SableCC (http://www.sablecc.org/). */

package Epl.node;

import Epl.analysis.*;

public final class X2PNonfid extends XPNonfid
{
    private PNonfid _pNonfid_;

    public X2PNonfid()
    {
    }

    public X2PNonfid(
        PNonfid _pNonfid_)
    {
        setPNonfid(_pNonfid_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PNonfid getPNonfid()
    {
        return _pNonfid_;
    }

    public void setPNonfid(PNonfid node)
    {
        if(_pNonfid_ != null)
        {
            _pNonfid_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pNonfid_ = node;
    }

    void removeChild(Node child)
    {
        if(_pNonfid_ == child)
        {
            _pNonfid_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pNonfid_);
    }
}
