/* This file was generated by SableCC (http://www.sablecc.org/). */

package Epl.node;

import Epl.analysis.*;

public final class X2PStatements extends XPStatements
{
    private PStatements _pStatements_;

    public X2PStatements()
    {
    }

    public X2PStatements(
        PStatements _pStatements_)
    {
        setPStatements(_pStatements_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PStatements getPStatements()
    {
        return _pStatements_;
    }

    public void setPStatements(PStatements node)
    {
        if(_pStatements_ != null)
        {
            _pStatements_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pStatements_ = node;
    }

    void removeChild(Node child)
    {
        if(_pStatements_ == child)
        {
            _pStatements_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pStatements_);
    }
}
