/* This file was generated by SableCC (http://www.sablecc.org/). */

package Epl.parser;

public class ParserException extends Exception
{
    public ParserException(String  message)
    {
        super(message);
    }
}
