/* This file was generated by SableCC (http://www.sablecc.org/). */

package Epl.parser;

import Epl.node.*;
import Epl.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    public void caseTFloatingConstant(TFloatingConstant node)
    {
        index = 0;
    }

    public void caseTFrozen(TFrozen node)
    {
        index = 1;
    }

    public void caseTTech(TTech node)
    {
        index = 2;
    }

    public void caseTRes(TRes node)
    {
        index = 3;
    }

    public void caseTTarg(TTarg node)
    {
        index = 4;
    }

    public void caseTNonft(TNonft node)
    {
        index = 5;
    }

    public void caseTNonpt(TNonpt node)
    {
        index = 6;
    }

    public void caseTBra(TBra node)
    {
        index = 7;
    }

    public void caseTKet(TKet node)
    {
        index = 8;
    }

    public void caseTSemicolon(TSemicolon node)
    {
        index = 9;
    }

    public void caseTArrow(TArrow node)
    {
        index = 10;
    }

    public void caseTIdentifier(TIdentifier node)
    {
        index = 11;
    }

    public void caseTCodecomment(TCodecomment node)
    {
        index = 12;
    }

    public void caseEOF(EOF node)
    {
        index = 13;
    }
}
